### ISSUE TITLE
Taunts

### ISSUE THREAD

**Issue by Rainrider** [AdiAddons/DRData-1.0#5]
Taunts DR works so that each taunt's duration after the first one is reduced by 35% up to a total of 5 taunts, at which point the creature becomes taunt immune. This is not supported by DRData currently.

Taunts DR is only implemented for some mobs apparently without a way to tell them apart.

**Comment by Adirelle** [comment]
Do you know which is the cooldown delay ? For normal DR, it's around 18 seconds.

**Comment by Adirelle** [comment]
This need to be tested.
