### ISSUE TITLE
Warlords spells

### ISSUE THREAD

**Issue by Rainrider** [AdiAddons/DRData-1.0#6]
You could take the wod ids from https://github.com/Rainrider/DRData-1.0/commits/wod . I didn't PR this as I see you made some changes too and I don't know how you would merge this.

**Comment by Rainrider** [comment]
Doh, @ascott18 already commited those

**Comment by Adirelle** [comment]
I renamed some categories in latest commit and added a deprecation warning for addons that would be still using the old names with the new version of the library.
